### ISSUE TITLE
Missing layer in one of the STL files

### ISSUE THREAD

**Issue by Jsanson1** [agordonfennell/headfixed_system#3]
Hello, I found an issue in the STL file titled "rotaryencoder_to_wheel_adapter". The model is missing a layer in the middle, causing each of the four adapters in the file to break into two pieces when 3D printed. 

I have attached a screenshot showing the gap in the model for reference. I also created a modified version that fills in this empty space, which has worked great for us so far. I attached a zip containing this updated STL file as well. 

Thanks!

- Jamie

![Gap](https://github.com/agordonfennell/OHRBETS/assets/161750793/529717da-ce09-4a91-a182-e46b87520561)
[Fixed_rotaryencoder_to_wheel_adapter.zip](https://github.com/user-attachments/files/16018321/Fixed_rotaryencoder_to_wheel_adapter.zip)

**Comment by gordon-laboratory** [comment]
Thank you for finding this problem Jamie. 

I have updated the model with the repaired version. 

- Adam
